const A={
 chicken:'assets/chicken-bites.png',
 crispy:'assets/crispy-chicken.png',
 feast:'assets/feast-box.png',
 bannerBurger:'assets/banner-burger.png',
 bannerMenu:'assets/banner-menu.png'
};
const products=[
 {id:'chicken-bites',name:'Chicken Bites',category:'Chicken',price:699,image:A.chicken,badge:'Fan favourite',desc:'Crispy little bites with a juicy centre and a golden, crackly finish.',ingredients:'Chicken breast, seasoned crumb, herbs, signature spice.',options:{'Piece quantity':['6 pieces','9 pieces','12 pieces'],'Spice level':['Mild','Classic','Hot'],'Optional drink':['No drink','Cola','Lemon fizz']}},
 {id:'crispy-chicken',name:'Crispy Chicken',category:'Chicken',price:799,image:A.crispy,badge:'Crispy pick',desc:'Crunchy, generously seasoned chicken made for big bites and bold dips.',ingredients:'Chicken, flour crumb, herbs, spices, house seasoning.',options:{'Portion':['Single','Double'],'Spice level':['Mild','Classic','Hot'],'Add side':['No side','Crust fries','Garden slaw']}},
 {id:'feast-box',name:'Feast Box',category:'Meals',price:1499,image:A.feast,badge:'Best value',desc:'A warm, shareable spread built for hungry tables and easy nights in.',ingredients:'Mixed savouries, buns, seasoned sides, dipping sauces.',options:{'Box size':['Solo','Classic','Big feast'],'Drink':['No drink','Cola','Lemon fizz'],'Side':['Crust fries','Garden slaw','Loaded wedges']}},
 {id:'smoky-burger',name:'Smoky Birch Burger',category:'Burgers',price:899,image:A.bannerBurger,badge:'New',desc:'A bold burger moment with a smoky, juicy centre and bright crunch.',ingredients:'Beef patty, toasted bun, lettuce, tomato, house sauce.',options:{'Patty':['Single','Double'],'Heat':['Classic','Hot'],'Side':['No side','Crust fries']}},
 {id:'crust-fries',name:'Crust Fries',category:'Sides',price:349,image:A.feast,badge:'Side',desc:'Golden seasoned fries with BirchLight’s warm crust spice.',ingredients:'Potatoes, seasoning, herbs.',options:{'Size':['Regular','Large']}},
 {id:'lemon-fizz',name:'Lemon Fizz',category:'Drinks',price:249,image:A.chicken,badge:'Fresh',desc:'Bright, chilled citrus fizz to cut through the crunch.',ingredients:'Sparkling water, lemon, citrus syrup.',options:{'Size':['Regular','Large']}}
];
const categories=['Chicken','Burgers','Meals','Sides','Drinks','Desserts'];
let cart=JSON.parse(localStorage.getItem('birchlight-cart')||'[]');
let state={slide:0,filter:'All',mobile:false,cart:false};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function money(n){return `Rs. ${n.toLocaleString()}`}
function saveCart(){localStorage.setItem('birchlight-cart',JSON.stringify(cart)); renderHeader();}
function cartCount(){return cart.reduce((a,x)=>a+x.qty,0)}
function cartTotal(){return cart.reduce((a,x)=>a+x.price*x.qty,0)}
function product(id){return products.find(p=>p.id===id)}
function icon(name){const icons={bag:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 8h12l1 12H5L6 8Z"/><path d="M9 8a3 3 0 0 1 6 0"/></svg>',menu:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 7h16M4 12h16M4 17h16"/></svg>',x:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 6 12 12M18 6 6 18"/></svg>',left:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><path d="m15 18-6-6 6-6"/></svg>',right:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><path d="m9 18 6-6-6-6"/></svg>',leaf:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 4C11 4 5 8 5 14c0 3 2 5 5 5 6 0 10-6 10-15Z"/><path d="M4 20c4-5 7-8 13-11"/></svg>'};return icons[name]||''}
function brand(){return `<a href="#/" class="brand" aria-label="BirchLight home"><span class="brand-mark">${icon('leaf')}</span><span class="brand-name">BirchLight</span></a>`}
function header(){const path=location.hash||'#/'; const active=path.startsWith('#/menu')||path.startsWith('#/category')?'Menu':path.startsWith('#/deals')?'Deals':path.startsWith('#/about')?'About':'Home'; return `<header class="site-header"><div class="container header-inner">${brand()}<nav class="main-nav" aria-label="Primary"><a class="nav-link ${active==='Home'?'active':''}" href="#/">Home</a><a class="nav-link ${active==='Menu'?'active':''}" href="#/menu">Menu</a><a class="nav-link ${active==='Deals'?'active':''}" href="#/deals">Deals</a><a class="nav-link ${active==='About'?'active':''}" href="#/about">About</a></nav><div class="header-actions"><a class="btn btn-red" href="#/menu">Order now</a><button class="icon-btn cart-trigger" id="cartBtn" aria-label="Open shopping cart">${icon('bag')}<span class="cart-count">${cartCount()}</span></button><button class="icon-btn hamburger" id="menuBtn" aria-label="Open menu">${icon('menu')}</button></div></div></header>`}
function footer(){return `<footer><div class="container"><div class="footer-top"><div class="footer-brand">${brand()}<p>Bold food, warm flavours, and a little more light in every bite. BirchLight is an original food-ordering experience built for the next craving.</p></div><div><div class="footer-title">Menu</div><div class="footer-links"><a href="#/category/chicken">Chicken</a><a href="#/category/burgers">Burgers</a><a href="#/category/meals">Meals</a><a href="#/category/sides">Sides</a></div></div><div><div class="footer-title">About</div><div class="footer-links"><a href="#/about">About BirchLight</a><a href="#/about">Our Story</a><a href="#/coming-soon">Contact</a></div></div><div><div class="footer-title">Help</div><div class="footer-links"><a href="#/coming-soon">FAQs</a><a href="#/coming-soon">Delivery</a><a href="#/checkout">Ordering</a></div></div></div><div class="footer-bottom"><span>© 2026 BirchLight. Original fictional brand experience.</span><span>Made for bold cravings.</span></div></div></footer>`}
function productCard(p){return `<article class="product-card" data-product="${p.id}"><a href="#/product/${p.id}" class="product-image-wrap"><img class="product-image" src="${p.image}" alt="${p.name}" loading="lazy"/><span class="badge ${p.badge==='Best value'?'gold':''}">${p.badge}</span></a><div class="product-body"><a href="#/product/${p.id}"><h3 class="product-name">${p.name}</h3></a><p class="product-desc">${p.desc}</p><div class="product-meta"><span class="price">${money(p.price)}</span><button class="add-btn" data-add="${p.id}">Add</button></div></div></article>`}
function categoryIcon(c){return ({Chicken:'🍗',Burgers:'🍔',Meals:'🥡',Sides:'🍟',Drinks:'🥤',Desserts:'🍪'})[c]||'✦'}
function categoriesBlock(active='All'){return `<section class="categories"><div class="container"><div class="category-row"><button class="category-btn ${active==='All'?'active':''}" data-category="All"><span class="category-icon">✦</span>All</button>${categories.map(c=>`<button class="category-btn ${active===c?'active':''}" data-category="${c}"><span class="category-icon">${categoryIcon(c)}</span>${c}</button>`).join('')}</div></div></section>`}
function hero(){return `<section class="hero" aria-label="BirchLight promotions"><div class="hero-viewport" id="heroViewport"><div class="hero-track" id="heroTrack"><a class="hero-slide" href="#/deals" aria-label="Burger offer"><img src="${A.bannerBurger}" alt="BirchLight burger limited offer"/></a><a class="hero-slide" href="#/coming-soon" aria-label="Fresh and healthy menu"><img src="${A.bannerMenu}" alt="BirchLight fresh and healthy food menu"/></a></div><button class="hero-control prev" id="heroPrev" aria-label="Previous slide">${icon('left')}</button><button class="hero-control next" id="heroNext" aria-label="Next slide">${icon('right')}</button><div class="hero-dots" id="heroDots"><button class="hero-dot active" aria-label="Slide 1"></button><button class="hero-dot" aria-label="Slide 2"></button></div></div></section>`}
function home(){return `<div>${hero()}<section class="order-strip"><div class="container order-strip-inner"><div><strong>READY TO ORDER?</strong><p>Get your BirchLight favourites moving while they’re hot.</p></div><div class="strip-actions"><a class="btn btn-red" href="#/menu">Order now</a><a class="btn btn-cream" href="#/deals">See deals</a></div></div></section>${categoriesBlock('All')}<section class="section" id="best"><div class="container"><div class="section-head"><div><div class="eyebrow">Made to crave</div><h2 class="section-title">Best Sellers</h2></div><p class="section-copy">Our boldest bites, warmest boxes, and quickest wins. Pick a favourite or discover your next one.</p></div><div class="product-grid">${products.slice(0,3).map(productCard).join('')}</div><div class="view-menu"><a class="btn btn-dark" href="#/menu">View full menu</a></div></div></section><section class="section deals"><div class="container"><div class="section-head"><div><div class="eyebrow">BirchLight specials</div><h2 class="section-title">Deals & heat</h2></div><p class="section-copy">Original BirchLight offers built around big flavours and easy ordering.</p></div><div class="deal-grid"><article class="deal-card"><div class="deal-visual"></div><div class="deal-content"><span class="deal-tag">Tonight's pick</span><h3>Crunch into something bold.</h3><p>Pair crispy chicken with a chilled drink and a warm side for a full BirchLight reset.</p><a class="btn btn-cream" href="#/product/crispy-chicken">Build yours</a></div></article><article class="deal-card small dark"><div class="deal-visual"></div><div class="deal-content"><span class="deal-tag">Share the light</span><h3>Feast mode.</h3><p>Big box, warm table, no overthinking.</p><a class="btn btn-red" href="#/product/feast-box">See Feast Box</a></div></article></div></div></section><section class="promo"><div class="container"><div class="promo-panel"><div><div class="eyebrow" style="color:var(--gold)">Freshly imagined</div><h2>Bring the bold home.</h2><p>From crisp bites to warm boxes, BirchLight keeps the menu focused, generous, and ready for your next craving.</p><a class="btn btn-cream" href="#/menu">Explore the menu</a></div><div class="promo-art" aria-hidden="true"></div></div></div></section><section class="section menu-band"><div class="container"><div class="section-head"><div><div class="eyebrow">More to discover</div><h2 class="section-title">Pick your mood</h2></div><p class="section-copy">Chicken, burgers, sides, drinks and more — browse the BirchLight way.</p></div>${categoriesBlock('All').replace('class="categories"','class="categories" style="padding-top:0"')}<div class="product-grid">${products.slice(3).map(productCard).join('')}</div></div></section>${footer()}</div>`}
function menuPage(filter=state.filter){const shown=filter==='All'?products:products.filter(p=>p.category===filter); return `<main class="page-shell"><section class="page-hero"><div class="container"><div class="eyebrow">BirchLight menu</div><h1 class="section-title">Pick your next bite.</h1><p class="section-copy">Browse the full menu and build your basket exactly how you like it.</p></div></section>${categoriesBlock(filter)}<section class="section" style="padding-top:28px"><div class="container"><div class="product-grid">${shown.length?shown.map(productCard).join(''):`<div class="preview-card" style="grid-column:1/-1"><div class="big-mark brand-mark">${icon('leaf')}</div><h1 class="display" style="font-size:3rem">Coming soon</h1><p>That category is being prepared. Try another BirchLight favourite.</p><a class="btn btn-red" href="#/menu">Back to menu</a></div>`}</div></div></section></main>${footer()}`}
function productPage(p){const firstOpts=Object.entries(p.options)[0]; return `<main class="page-shell"><section class="page-hero"><div class="container"><div class="crumbs"><a href="#/">Home</a> / <a href="#/menu">Menu</a> / ${p.name}</div><div class="product-detail"><div class="detail-image"><img src="${p.image}" alt="${p.name}"/></div><div class="detail-info"><div class="eyebrow">${p.category}</div><h1>${p.name}</h1><div class="detail-price" id="detailPrice">${money(p.price)}</div><p class="detail-description">${p.desc}</p>${Object.entries(p.options).map(([label,opts],i)=>`<div class="option-group"><div class="option-label">${label}</div><div class="option-list">${opts.map((o,j)=>`<button class="option-btn ${j===0?'selected':''}" data-option="${label}" data-value="${o}">${o}</button>`).join('')}</div></div>`).join('')}<div class="option-label">Quantity</div><div class="quantity"><button id="qtyMinus" aria-label="Decrease quantity">−</button><span id="qty">1</span><button id="qtyPlus" aria-label="Increase quantity">+</button></div><div class="detail-actions"><button class="btn btn-red" id="detailAdd" data-product="${p.id}">Add to basket</button><button class="btn btn-dark" id="detailOrder" data-product="${p.id}">Order now</button></div><div class="info-box"><strong>Ingredients</strong><p>${p.ingredients}</p></div><div class="info-box"><strong>BirchLight note</strong><p>Prepared as an original BirchLight menu concept. Options shown here are frontend preview choices and do not process payment.</p></div></div></div></div></section><section class="related"><div class="container"><div class="section-head"><div><div class="eyebrow">You might also like</div><h2 class="section-title">Keep the table warm.</h2></div></div><div class="product-grid">${products.filter(x=>x.id!==p.id).slice(0,3).map(productCard).join('')}</div></div></section></main>${footer()}`}
function dealsPage(){return `<main class="page-shell"><section class="page-hero"><div class="container"><div class="eyebrow">Limited & original</div><h1 class="section-title">Deals with BirchLight energy.</h1><p class="section-copy">Promotional concepts for this frontend experience — no fake payment or unavailable service claims.</p></div></section><section class="section"><div class="container"><div class="deal-grid"><article class="deal-card" style="background:var(--red);min-height:430px"><div class="deal-visual"></div><div class="deal-content"><span class="deal-tag">Crunch pick</span><h3>Crispy chicken, your way.</h3><p>Choose your portion, heat level and side, then send it to your basket.</p><a class="btn btn-cream" href="#/product/crispy-chicken">Customize</a></div></article><article class="deal-card small dark" style="min-height:430px"><div class="deal-visual"></div><div class="deal-content"><span class="deal-tag">Table builder</span><h3>Feast Box.</h3><p>Choose the box size, drink and side for a flexible meal setup.</p><a class="btn btn-red" href="#/product/feast-box">Build a box</a></div></article></div></div></section></main>${footer()}`}
function aboutPage(){return `<main class="page-shell"><section class="preview"><div class="preview-card"><div class="big-mark brand-mark">${icon('leaf')}</div><div class="eyebrow">The BirchLight idea</div><h1>Warm food. Bright energy.</h1><p>BirchLight is a fictional original food brand created for this standalone ordering experience. The identity blends charcoal, cream, chili red and crust gold with bold food-first interactions.</p><a class="btn btn-red" href="#/menu">Explore the menu</a></div></section></main>${footer()}`}
function comingSoon(){return `<main class="preview page-shell"><div class="preview-card"><div class="big-mark brand-mark">${icon('leaf')}</div><div class="eyebrow">BirchLight preview</div><h1>Coming Soon</h1><p>This BirchLight experience is currently being prepared. You can continue shopping or return home.</p><div class="detail-actions" style="justify-content:center"><a class="btn btn-red" href="#/menu">Continue shopping</a><a class="btn btn-dark" href="#/">Back home</a></div></div></main>`}
function checkout(){return `<main class="page-shell"><section class="page-hero"><div class="container"><div class="eyebrow">Frontend preview</div><h1 class="section-title">BirchLight Checkout</h1><p class="section-copy">Online ordering is currently being prepared. Your basket is preserved for the next step.</p></div></section><div class="checkout-summary">${cart.length?cart.map(x=>`<div class="summary-item"><span>${x.name} × ${x.qty}<small style="display:block;color:var(--muted)">${Object.values(x.options||{}).join(' · ')}</small></span><strong>${money(x.price*x.qty)}</strong></div>`).join(''):`<div class="cart-empty"><div class="empty-icon">🛒</div><strong>Your basket is empty.</strong><p>Add something delicious first.</p></div>`}<div class="total-row" style="margin-top:20px"><span>Total</span><strong>${money(cartTotal())}</strong></div><div class="detail-actions"><a class="btn btn-red" href="#/menu">Continue Shopping</a><a class="btn btn-dark" href="#/">Back Home</a></div></div></main>${footer()}`}
function render(){const hash=location.hash||'#/';let content;if(hash==='#/'||hash==='#')content=home();else if(hash==='#/menu')content=menuPage('All');else if(hash.startsWith('#/category/')){const c=hash.split('/')[2];state.filter=c.charAt(0).toUpperCase()+c.slice(1);content=menuPage(state.filter)}else if(hash==='#/deals')content=dealsPage();else if(hash==='#/about')content=aboutPage();else if(hash==='#/checkout')content=checkout();else if(hash==='#/coming-soon')content=comingSoon();else if(hash.startsWith('#/product/')){const p=product(hash.split('/')[2]);content=p?productPage(p):comingSoon()}else content=comingSoon();$('#app').innerHTML=header()+content+drawers();bind();window.scrollTo(0,0)}
function drawers(){return `<div class="scrim" id="scrim"></div><aside class="cart-drawer" id="cartDrawer" aria-label="Shopping cart"><div class="cart-head"><h2>Your Basket</h2><button class="close-btn" id="closeCart" aria-label="Close cart">×</button></div><div class="cart-body">${cart.length?cart.map((x,i)=>`<div class="cart-item"><img src="${x.image}" alt="${x.name}"/><div><h3>${x.name}</h3><div class="cart-options">${Object.values(x.options||{}).join(' · ')}</div><div class="cart-controls"><button class="mini-q" data-cart-dec="${i}">−</button><strong>${x.qty}</strong><button class="mini-q" data-cart-inc="${i}">+</button><button class="remove" data-remove="${i}">Remove</button></div></div><div class="cart-item-price">${money(x.price*x.qty)}</div></div>`).join(''):`<div class="cart-empty"><div class="empty-icon">✦</div><strong>Your basket is waiting.</strong><p>Add a BirchLight favourite and it will appear here.</p><a class="btn btn-red" href="#/menu" id="emptyMenu">Browse menu</a></div>`}</div><div class="cart-foot"><div class="total-row"><span>Total</span><strong>${money(cartTotal())}</strong></div><a class="btn btn-red checkout-btn" href="#/checkout">Checkout</a></div></aside><aside class="mobile-drawer" id="mobileDrawer"><div class="mobile-head">${brand()}<button class="close-btn" id="closeMobile" aria-label="Close menu">${icon('x')}</button></div><nav class="mobile-links"><a href="#/">Home</a><a href="#/menu">Menu</a><a href="#/deals">Deals</a><a href="#/about">About</a></nav><a class="btn btn-red mobile-order" href="#/menu">Order now</a></aside><div class="toast" id="toast" role="status"></div>`}
function renderHeader(){const count=$('.cart-count');if(count)count.textContent=cartCount()}
function openCart(){state.cart=true;$('#cartDrawer')?.classList.add('open');$('#scrim')?.classList.add('show');document.body.classList.add('locked')}
function closeCart(){state.cart=false;$('#cartDrawer')?.classList.remove('open');if(!state.mobile)$('#scrim')?.classList.remove('show');document.body.classList.remove('locked')}
function openMobile(){state.mobile=true;$('#mobileDrawer')?.classList.add('open');$('#scrim')?.classList.add('show');document.body.classList.add('locked')}
function closeMobile(){state.mobile=false;$('#mobileDrawer')?.classList.remove('open');if(!state.cart)$('#scrim')?.classList.remove('show');document.body.classList.remove('locked')}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),2200)}
function addToCart(p,qty=1,options={}){const key=p.id+'|'+JSON.stringify(options);const existing=cart.find(x=>x.key===key);if(existing)existing.qty+=qty;else cart.push({key,id:p.id,name:p.name,price:p.price,image:p.image,qty,options});saveCart();toast(`${p.name} added to basket`);openCart();}
function bind(){
 $('#cartBtn')?.addEventListener('click',openCart); $('#menuBtn')?.addEventListener('click',openMobile); $('#closeCart')?.addEventListener('click',closeCart); $('#closeMobile')?.addEventListener('click',closeMobile); $('#scrim')?.addEventListener('click',()=>{closeCart();closeMobile()});
 $$('[data-add]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const p=product(b.dataset.add);addToCart(p)}));
 $$('[data-category]').forEach(b=>b.addEventListener('click',()=>{const c=b.dataset.category;location.hash=c==='All'?'#/menu':'#/category/'+c.toLowerCase()}));
 $$('[data-cart-inc]').forEach(b=>b.addEventListener('click',()=>{cart[b.dataset.cartInc].qty++;saveCart();render() }));
 $$('[data-cart-dec]').forEach(b=>b.addEventListener('click',()=>{const x=cart[b.dataset.cartDec];x.qty=Math.max(1,x.qty-1);saveCart();render()}));
 $$('[data-remove]').forEach(b=>b.addEventListener('click',()=>{cart.splice(+b.dataset.remove,1);saveCart();render();openCart()}));
 const track=$('#heroTrack');if(track){let timer;const dots=$$('.hero-dot');const setSlide=i=>{state.slide=(i+2)%2;track.style.transform=`translateX(-${state.slide*100}%)`;dots.forEach((d,j)=>d.classList.toggle('active',j===state.slide))};$('#heroPrev').addEventListener('click',()=>{setSlide(state.slide-1);restart()});$('#heroNext').addEventListener('click',()=>{setSlide(state.slide+1);restart()});dots.forEach((d,i)=>d.addEventListener('click',()=>{setSlide(i);restart()}));const start=()=>timer=setInterval(()=>setSlide(state.slide+1),5200);const stop=()=>clearInterval(timer);const restart=()=>{stop();start()};$('#heroViewport').addEventListener('mouseenter',stop);$('#heroViewport').addEventListener('mouseleave',start);start()}
 const qty=$('#qty');if(qty){let q=1;const price=product($('#detailAdd').dataset.product).price;const update=()=>{$('#qty').textContent=q;$('#detailPrice').textContent=money(price*q)};$('#qtyMinus').addEventListener('click',()=>{q=Math.max(1,q-1);update()});$('#qtyPlus').addEventListener('click',()=>{q++;update()});$$('.option-btn').forEach(btn=>btn.addEventListener('click',()=>{$$(`.option-btn[data-option="${CSS.escape(btn.dataset.option)}"]`).forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')}));const collect=()=>{const o={};$$('.option-btn.selected').forEach(x=>o[x.dataset.option]=x.dataset.value);return o};$('#detailAdd').addEventListener('click',()=>addToCart(product($('#detailAdd').dataset.product),q,collect()));$('#detailOrder').addEventListener('click',()=>{addToCart(product($('#detailOrder').dataset.product),q,collect());location.hash='#/checkout'});}
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closeMobile() }},{once:true});
}
window.addEventListener('hashchange',render);window.addEventListener('load',render);
